kind: Template
apiVersion: v1
labels:
  template: "jenkins-master"
metadata:
  name: "jenkins-master"
  annotations:
    openshift.io/display-name: "Jenkins Master"
    description: "Jenkins service, with persistent storage.\n\nNOTE: You must have persistent volumes available in your cluster to use this template."
    iconClass: "icon-jenkins"
    tags: "instant-app,jenkins-master,jenkins"
    template.openshift.io/long-description: "This template deploys a Jenkins server."
    template.openshift.io/provider-display-name: "Wen Hao."
    template.openshift.io/documentation-url: "https://github.com/wenhao/openshift-jenkins"
    template.openshift.io/support-url: "https://github.com/wenhao/openshift-jenkins"
message: "A Jenkins service has been created in your project.  Log into Jenkins with defualt admin account."
objects:
  - kind: DeploymentConfig
    apiVersion: v1
    metadata:
      name: "${JENKINS_NAME}"
      labels:
        app: "${JENKINS_NAME}"
    spec:
      replicas: 1
      selector:
        app: "${JENKINS_NAME}"
      strategy:
        type: "Recreate"
      triggers:
        - type: "ImageChange"
          imageChangeParams:
            automatic: true
            containerNames:
              - jenkins-master
            from:
              kind: "ImageStreamTag"
              name: "${IMAGE_STREAM_TAG}"
              namespace: "${NAMESPACE}"
        - type: "ConfigChange"
      template:
        metadata:
          labels:
            app: "${JENKINS_NAME}"
        spec:
          containers:
            - name: "jenkins-master"
              image: "jenkins-master"
              imagePullPolicy: "IfNotPresent"
              readinessProbe:
                timeoutSeconds: 3
                initialDelaySeconds: 3
                httpGet:
                  path: "/login"
                  port: 8080
              livenessProbe:
                timeoutSeconds: 3
                initialDelaySeconds: 420
                failureThreshold: 30
                httpGet:
                  path: "/login"
                  port: 8080
              env:
                - name: "JENKINS_ADMIN_USERNAME"
                  value: "${USERNAME}"
                - name: "JENKINS_ADMIN_PASSWORD"
                  value: "${PASSWORD}"
                - name: "HOME"
                  value: "${HOME}"
              resources:
                requests:
                  memory: "512Mi"
                limits:
                  memory: "${MEMORY_LIMIT}"
              volumeMounts:
                - name: "${JENKINS_NAME}-data"
                  mountPath: "${HOME}"
              terminationMessagePath: "/dev/termination-log"
              securityContext:
                privileged: false
          volumes:
            - name: "${JENKINS_NAME}-data"
              persistentVolumeClaim:
                claimName: "${JENKINS_NAME}"
          restartPolicy: "Always"
          dnsPolicy: "ClusterFirst"
  - kind: Service
    apiVersion: v1
    metadata:
      name: "${JENKINS_NAME}"
      labels:
        app: "${JENKINS_NAME}"
      annotations:
        service.openshift.io/infrastructure: "true"
    spec:
      ports:
        - name: "jenkins-master-web"
          protocol: "TCP"
          port: 80
          targetPort: 8080
      selector:
        app: "${JENKINS_NAME}"
      type: "ClusterIP"
      sessionAffinity: "None"
  - kind: Service
    apiVersion: v1
    metadata:
      name: "${JENKINS_NAME}-jenkins-slave"
      labels:
        app: "${JENKINS_NAME}"
      annotations:
        service.openshift.io/infrastructure: "true"
    spec:
      ports:
        - name: "jenkins-slave"
          protocol: "TCP"
          port: 50000
          targetPort: 50000
      selector:
        app: "${JENKINS_NAME}"
      type: "ClusterIP"
      sessionAffinity: "None"
  - kind: Route
    apiVersion: v1
    metadata:
      name: "${JENKINS_NAME}"
      labels:
        app: "${JENKINS_NAME}"
      annotations:
        template.openshift.io/expose-uri: "http://{.spec.host}{.spec.path}"
    spec:
      to:
        kind: Service
        name: "${JENKINS_NAME}-jenkins-master"
  - kind: PersistentVolumeClaim
    apiVersion: v1
    metadata:
      name: "${JENKINS_NAME}"
      labels:
        app: "${JENKINS_NAME}"
    spec:
      accessModes:
        - ReadWriteMany
      resources:
        requests:
          storage: "${VOLUME_CAPACITY}"
parameters:
  - name: "JENKINS_NAME"
    displayName: "Jenkins Master Server Name"
    description: "The unqiue name of the Jenkins Service And Route."
    value: "jenkins"
    required: true
  - name: "USERNAME"
    displayName: "Jenkins Master Administrator Username"
    description: "Username of the Jenkins Master Administrator."
    value: "admin"
    required: true
  - name: "PASSWORD"
    displayName: "Jenkins Master Administrator Password"
    description: "Password of the Jenkins Master Administrator."
    value: "admin"
    required: true
  - name: "HOME"
    displayName: "Jenkins Home Directory"
    description: "Directory of the Jenkins Home."
    value: "/var/jenkins_home"
    required: true
  - name: "NAMESPACE"
    displayName: "OpenShift Working Namespace"
    description: "The OpenShift Working Namespace."
    value: "devops"
    required: true
  - name: "IMAGE_STREAM_TAG"
    displayName: "Jenkins ImageStreamTag"
    description: "Name of the ImageStreamTag to be used for the Jenkins image."
    value: "openshift-jenkins-master:v1.0.0"
    required: true
  - name: "MEMORY_LIMIT"
    displayName: "Memory Limit"
    description: "Maximum amount of memory the container can use."
    value: "2Gi"
    required: true
  - name: "VOLUME_CAPACITY"
    displayName: "Volume Capacity"
    description: "Volume space available for data, e.g. 512Mi, 2Gi."
    value: "10Gi"
    required: true
